name: GitHub Actions Demo
on: [push]
jobs:  
  example-job:
    runs-on: ubuntu-latest
    steps:    
      - name: Run build script
        uses: actions/checkout@v2
        run: ./.github/scripts/release.sh