name: GitHub Actions Demo
on: [push]
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run build script
        run: |
          pwd
          ./scripts/release.sh
        shell: bash