name: release
on: 
  push:    
    tags:
      - v*
  workflow_dispatch:
jobs:  
  release:
    runs-on: ubuntu-latest
    secrets:
      YANDEX_TOKEN: ${{ secrets.YANDEX_TOKEN }}
      YANDEX_XORG_ID: ${{ secrets.YANDEX_ORG_ID }}    
    steps:          
      - uses: actions/checkout@v2
        with:
          ref: 'master'
          fetch-depth: 0
      - run: git checkout ${{ github.ref }}                
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: ./.github/scripts/release.sh          
        env: 
          YANDEX_TOKEN: ${{ secrets.YANDEX_TOKEN }}
          YANDEX_XORG_ID: ${{ secrets.YANDEX_ORG_ID }}    
          GGITHUB_SERVER_URL: ${{ github.GITHUB_SERVER_URL }}
          GGITHUB_REPOSITORY: ${{ github.GITHUB_REPOSITORY }}
          GGITHUB_RUN_ID: ${{ github.GITHUB_RUN_ID }}